import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/header";
import { ThemeProvider } from "next-themes";
import { UserProvider } from '@auth0/nextjs-auth0/client';

export const viewport = {
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: 'white' },
    { media: '(prefers-color-scheme: dark)', color: 'black' }
  ]
};

export const metadata: Metadata = {
  title: "Stice AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body>
          <UserProvider>
            <Header />
              <ThemeProvider attribute="class" defaultTheme="system" disableTransitionOnChange>
                <div suppressHydrationWarning>
                  {typeof window === "undefined" ? null : children}
                </div>
                <main className="flex flex-col flex-1">
                  {children}
                </main>
              </ThemeProvider>
          </UserProvider>
        </body>
    </html>
  );
}